model:
    name: two_view_pipeline
    extractor:
        name: extractors.sift
        backend: py_cudasift
        max_num_keypoints: 4096
        force_num_keypoints: False
        nms_radius: 0
        trainable: False
        detection_threshold: 1.7  # 1.7 0.4   
        rootsift: false
        first_octave: -1
        num_octaves: 6          # 6  3
        init_blur: 1.0          # 1 2.0
        filter_kpts_with_wrapper: False
        filter_with_scale_weighting: True
        extractor_channel: grayscale
        filter_with_lowest_scale: false
    matcher:
      name: matchers.lightglue_pretrained
      features: sift
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024  # overwrite config above
