
# checkpoint: outputs/training/long26_gt_pos_null_10_lg1e-03_lr5e-05_5bin/checkpoint_best.tar
checkpoint: outputs/training/sift_pycolmap_cuda+lightglue_homography/checkpoint_best.tar

model:
    name: two_view_pipeline
    extractor:
      name: extractors.sift
      backend: pycolmap_cuda
      max_num_keypoints: 4096
      detection_threshold: 0.0066667
      rootsift: true
      nms_radius: 0
      first_octave: -1
      num_octaves: 4
      init_blur: 1.0
      extractor_channel: grayscale


    matcher:
      name: matchers.lightglue
      features: sift
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
      input_dim: 128      
      add_scale_ori: false

benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024  # overwrite config above
